theme: jekyll-theme-cayman
title: GameToolBox
description: Go + Fyne 游戏工具箱

# 关键：仓库型 Pages 需要 baseurl = /<repo>
baseurl: "/GameToolBox"
url: "https://jiangxincode.github.io"

markdown: kramdown

exclude:
  - README.md
